info:
  name: Create Application
  type: http
  seq: 3

http:
  method: POST
  url: http://localhost:8080/api/applications
  body:
    type: json
    data: |-
      {
        "link": "https://www.digitalextremes.com/careers/position/5169126007",
        "company": "Digital Extremes",
        "location": "London, ON",
        "salary": "80k-95k / year",
        "jobType": "Dont Know",
        "applicationDeadline": null,
        "postingPlatform": "Company's Site"
      }
  auth:
    type: bearer
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJnZW9mZnJleUBleGFtcGxlLmNvbSIsImlhdCI6MTc5MDQwMDkzMiwiZXhwIjoxNzkwNDg3MzMyfQ.hsBPH7o8NZxQ4-Jhy1YOKx3NAUAQe9_SU4DLVgu7niCRmZ_LqffsrPDs7Amm1LX7SjIIX40PLSk6UOSL0tzuAw

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
