info:
  name: Delete Application
  type: http
  seq: 5

http:
  method: DELETE
  url: http://localhost:8080/api/applications/1
  auth:
    type: bearer
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJnZW9mZnJleUBleGFtcGxlLmNvbSIsImlhdCI6MTc5MDA2MTYwNSwiZXhwIjoxNzkwMTQ4MDA1fQ.7KMVwQk04nkowmFJiFSzgZnIIoEtj2uopOy7E-E41VFTqGks8TApQarc_cEa7A-XKZwhntoKrNqq2js4M4Zciw

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
