info:
  name: Update Application Patch
  type: http
  seq: 6

http:
  method: PATCH
  url: http://localhost:8080/api/applications/1
  body:
    type: json
    data: |-
      {
        "jobType": "Dont Knowwer"
      }
  auth:
    type: bearer
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJnZW9mZnJleUBleGFtcGxlLmNvbSIsImlhdCI6MTc5MDA0MzAxNCwiZXhwIjoxNzkwMTI5NDE0fQ.OpydVyOyzYOQ2YWnvnW6dAxYmoDLmnwZtLwU3T7l1Rr5GiZBfbnOWepQrmoYlJiEKkdi-rWcirugM10Jij7fPg

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
