info:
  name: Update Application Patch
  type: http
  seq: 6

http:
  method: PATCH
  url: http://localhost:8080/api/applications/2
  body:
    type: json
    data: |-
      {
        "jobType": "Dont Know"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
