info:
  name: Update Application
  type: http
  seq: 4

http:
  method: PUT
  url: http://localhost:8080/api/applications/1
  body:
    type: json
    data: |-
      {
        "link": "https://www.digitalextremes.com/careers/position/5169126007",
        "location": "London, ON",
        "salary": "80k-95k / year",
        "jobType": "Dont Knoww",
        "applicationDeadline": null,
        "postingPlatform": "Company's Site"
      }
  auth:
    type: bearer
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJnZW9mZnJleUBleGFtcGxlLmNvbSIsImlhdCI6MTc5MDA0MzAxNCwiZXhwIjoxNzkwMTI5NDE0fQ.OpydVyOyzYOQ2YWnvnW6dAxYmoDLmnwZtLwU3T7l1Rr5GiZBfbnOWepQrmoYlJiEKkdi-rWcirugM10Jij7fPg

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
